name: 恢复singbox服务并发送Telegram消息

on:
  schedule:
    - cron: '0 0 */4 * *'  # 每4天执行一次
  workflow_dispatch:

jobs:
  restore_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装sshpass
        run: sudo apt-get install -y sshpass

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 执行Python脚本恢复singbox服务并发送Telegram消息
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 recover_singbox.py
        continue-on-error: true

      - name: 打印Python脚本输出日志
        if: failure()  # 仅在上一步失败时执行
        run: cat recover_singbox.log || true
