name: Recover Singbox Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 # 更新到 v3

    - name: Set up Python
      uses: actions/setup-python@v3 # 更新到 v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run recover_singbox.py
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python recover_singbox.py
