name: Recover Singbox Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  recover:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install requests

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: List files
      run: ls -la

    - name: Debug environment variables
      run: |
        echo "ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}"
        echo "TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}"
        echo "TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}"

    - name: Run recover_singbox.py
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python3 recover_singbox.py || { echo 'Python script failed'; exit 1; }
